spring:
  application:
    name: gateway
#  redis:
#    database: 10
#    host: 192.168.96.12
#    port: 6379
#    pool:
#      max-idle: 8
#      min-idle: 1
#      max-active: 8
#      max-wait: -1

server:
  port: 5001

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://registry:5000/eureka/

zuul:
  ratelimit:
    enabled: true
    behind-proxy: true
    key-prefix: ${spring.application.name}
#    repository: REDIS
    repository: IN_MEMORY
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 1 #optional - request number limit per refresh interval window
        quota: 1 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 1 #default value (in seconds)
        type: #optional
          - user
          - origin
          - url
    policies:
      api-service:
        limit: 2
        quota: 1
        refresh-interval: 3
#  ignoredServices: '*'
  routes:
    api-service:
      path: /api-service/**
      serviceId: api-service
  # 影响MaxAutoRetries MaxAutoRetriesNextServer
  retryable: false

management:
  security:
    enabled: false


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
#  #对当前服务的重试次数，要做接口数据一致性机制
  MaxAutoRetries: 1
#  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0


#authserver:
#    hostname: auth-service
#    port: 5000
#    contextPath: /uaa

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current