spring:
  application:
    name: api-service

server:
  port: 5003

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://registry:5000/eureka/
