spring:
  application:
    name: gateway

server:
  port: 5001

eureka:
  client:
    service-url:
      defaultZone: http://registry:5000/eureka/

zuul:
#  ignoredServices: '*'
  routes:
    api-service:
      path: /api-service/**
      serviceId: api-service


#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000


#authserver:
#    hostname: auth-service
#    port: 5000
#    contextPath: /uaa

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current